---
# tasks file for sbaerlocher.yaourt
- name: "add archlinux.fr repository to pacman"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  when: ansible_distribution == "ArchLinux"

- name: "install yaourt"
  pacman:
    name: "yaourt"
    state: "present"
  when: ansible_distribution == "ArchLinux"